In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/ekver/OneDrive/Documents/Job_Preparation/Customer_Retention_Project/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
df.describe(include="all")

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7590-VHVEG,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [18]:
df["customerID"].nunique()

7043

In [19]:
len(df)

7043

In [20]:
df["customerID"].duplicated().sum()

np.int64(0)

In [21]:
df["Churn"].value_counts(dropna=False)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [22]:
df["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [23]:
df["customerID"].nunique()

7043

In [24]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df["customerID"].duplicated().sum()

np.int64(0)

In [27]:
df.shape

df["customerID"].nunique()

df.info()

df.isna().sum()

df.duplicated().sum()

df["customerID"].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

np.int64(0)

In [28]:
df["TotalCharges"].head(20)

0       29.85
1      1889.5
2      108.15
3     1840.75
4      151.65
5       820.5
6      1949.4
7       301.9
8     3046.05
9     3487.95
10     587.45
11      326.8
12     5681.1
13     5036.3
14    2686.05
15    7895.15
16    1022.95
17    7382.25
18     528.35
19     1862.9
Name: TotalCharges, dtype: str

In [29]:
(df["TotalCharges"].str.strip() == "").sum()

np.int64(11)

In [30]:
totalcharges_numeric = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

invalid_totalcharges = df[
    totalcharges_numeric.isna()
]

invalid_totalcharges[
    [
        "customerID",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "Contract",
        "Churn"
    ]
]

      customerID  tenure  MonthlyCharges TotalCharges  Contract Churn
488   4472-LVYGI       0           52.55               Two year    No
753   3115-CZMZD       0           20.25               Two year    No
936   5709-LVOEQ       0           80.85               Two year    No
1082  4367-NUYAO       0           25.75               Two year    No
1340  1371-DWPAZ       0           56.05               Two year    No
3331  7644-OMVMY       0           19.85               Two year    No
3826  3213-VVOLG       0           25.35               Two year    No
4380  2520-SGTTA       0           20.00               Two year    No
5218  2923-ARZLG       0           19.70               One year    No
6670  4075-WKNIU       0           73.35               Two year    No
6754  2775-SEFEE       0           61.90               Two year    No

In [31]:
len(invalid_totalcharges)

11

In [32]:
categorical_cols = df.select_dtypes(include="str").columns

for col in categorical_cols:
    print(f"\n========== {col} ==========")
    print(df[col].value_counts(dropna=False))

========== customerID ==========
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

========== gender ==========
gender
Male      3555
Female    3488
Name: count, dtype: int64

========== Partner ==========
Partner
No     3641
Yes    3402
Name: count, dtype: int64

========== Dependents ==========
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

========== PhoneService ==========
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

========== MultipleLines ==========
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

========== InternetService ==========
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

========== OnlineSecurity ==========
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

========== OnlineBackup ==========
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

========== DeviceProtection ==========
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

========== TechSupport ==========
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

========== StreamingTV ==========
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

========== StreamingMovies ==========
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

========== Contract ==========
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

========== PaperlessBilling ==========
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

========== PaymentMethod ==========
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

========== TotalCharges ==========
TotalCharges
20.2      11
          11
19.75      9
19.9       8
20.05      8
          ..
1990.5     1
7362.9     1
346.45     1
306.6      1
6844.5     1
Name: count, Length: 6531, dtype: int64

========== Churn ==========
Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [33]:
df[df["TotalCharges"].str.strip() == ""]["tenure"].value_counts()

tenure
0    11
Name: count, dtype: int64

==============
#Data Cleaning
==============

In [34]:
df_clean = df.copy()

In [35]:
df_clean.shape

(7043, 21)

In [36]:
df_clean["TotalCharges"] = pd.to_numeric(
    df_clean["TotalCharges"].str.strip(),
    errors="coerce"
)

In [37]:
df_clean["TotalCharges"].dtype

dtype('float64')

In [38]:
df_clean["TotalCharges"].isna().sum()

np.int64(11)

In [39]:
df_clean[df_clean["TotalCharges"].isna()][
    [
        "customerID",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "Contract",
        "Churn"
    ]
]

      customerID  tenure  MonthlyCharges  TotalCharges  Contract Churn
488   4472-LVYGI       0           52.55           NaN  Two year    No
753   3115-CZMZD       0           20.25           NaN  Two year    No
936   5709-LVOEQ       0           80.85           NaN  Two year    No
1082  4367-NUYAO       0           25.75           NaN  Two year    No
1340  1371-DWPAZ       0           56.05           NaN  Two year    No
3331  7644-OMVMY       0           19.85           NaN  Two year    No
3826  3213-VVOLG       0           25.35           NaN  Two year    No
4380  2520-SGTTA       0           20.00           NaN  Two year    No
5218  2923-ARZLG       0           19.70           NaN  One year    No
6670  4075-WKNIU       0           73.35           NaN  Two year    No
6754  2775-SEFEE       0           61.90           NaN  Two year    No

In [40]:
df_clean.loc[
    df_clean["TotalCharges"].isna(),
    "tenure"
].unique()

array([0])

Tenure = 0
TotalCharges = unavailable
=> Customers with zero tenure and blank accumulated charges are treated as having zero accumulated charges for analytical calculations.

In [41]:
df_clean["TotalCharges"] = df_clean["TotalCharges"].fillna(0)

In [42]:
df_clean.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [43]:
df_clean.duplicated().sum()

np.int64(0)

In [44]:
df_clean["customerID"].duplicated().sum()

np.int64(0)

=====================
#Check numeric ranges:
======================

In [45]:
df_clean[[
    "SeniorCitizen",
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]].describe().T

,count,mean,std,min,25%,50%,75%,max
SeniorCitizen,7043.0,0.162147,0.368612,0.00,0.00,0.00,0.00,1.00
tenure,7043.0,32.371149,24.559481,0.00,9.00,29.00,55.00,72.00
MonthlyCharges,7043.0,64.761692,30.090047,18.25,35.50,70.35,89.85,118.75
TotalCharges,7043.0,2279.734304,2266.794470,0.00,398.55,1394.55,3786.60,8684.80

In [46]:
print("Tenure:", df_clean["tenure"].min(), "to", df_clean["tenure"].max())
print("Monthly Charges:", df_clean["MonthlyCharges"].min(), "to", df_clean["MonthlyCharges"].max())
print("Total Charges:", df_clean["TotalCharges"].min(), "to", df_clean["TotalCharges"].max())

Tenure: 0 to 72
Monthly Charges: 18.25 to 118.75
Total Charges: 0.0 to 8684.8

===============================
#Check categorical consistency
===============================

In [47]:
categorical_cols = df_clean.select_dtypes(
    include="str"
).columns

for col in categorical_cols:
    print(f"\n===== {col} =====")
    print(df_clean[col].value_counts(dropna=False))

===== customerID =====
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

===== gender =====
gender
Male      3555
Female    3488
Name: count, dtype: int64

===== Partner =====
Partner
No     3641
Yes    3402
Name: count, dtype: int64

===== Dependents =====
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

===== PhoneService =====
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

===== MultipleLines =====
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

===== InternetService =====
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

===== OnlineSecurity =====
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

===== OnlineBackup =====
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

===== DeviceProtection =====
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

===== TechSupport =====
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

===== StreamingTV =====
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

===== StreamingMovies =====
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

===== Contract =====
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

===== PaperlessBilling =====
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

===== PaymentMethod =====
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

===== Churn =====
Churn
No     5174
Yes    1869
Name: count, dtype: int64

#Check business rule

In [48]:
df_clean["SeniorCitizen"].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [49]:
df_clean["tenure"].value_counts().sort_index()

tenure
0      11
1     613
2     238
3     200
4     176
     ...
68    100
69     95
70    119
71    170
72    362
Name: count, Length: 73, dtype: int64

In [50]:
df_clean[df_clean["tenure"] == 0][
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Contract", "Churn"]
]

      customerID  tenure  MonthlyCharges  TotalCharges  Contract Churn
488   4472-LVYGI       0           52.55           0.0  Two year    No
753   3115-CZMZD       0           20.25           0.0  Two year    No
936   5709-LVOEQ       0           80.85           0.0  Two year    No
1082  4367-NUYAO       0           25.75           0.0  Two year    No
1340  1371-DWPAZ       0           56.05           0.0  Two year    No
3331  7644-OMVMY       0           19.85           0.0  Two year    No
3826  3213-VVOLG       0           25.35           0.0  Two year    No
4380  2520-SGTTA       0           20.00           0.0  Two year    No
5218  2923-ARZLG       0           19.70           0.0  One year    No
6670  4075-WKNIU       0           73.35           0.0  Two year    No
6754  2775-SEFEE       0           61.90           0.0  Two year    No

In [51]:
df_clean[df_clean["tenure"] == 0]["TotalCharges"].value_counts()

TotalCharges
0.0    11
Name: count, dtype: int64

In [52]:
#Check for logically suspicious revenue records

suspicious_charges = df_clean[
    (df_clean["tenure"] > 1) &
    (df_clean["TotalCharges"] < df_clean["MonthlyCharges"])
]

suspicious_charges[
    [
        "customerID",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "Contract",
        "Churn"
    ]
]

Empty DataFrame
Columns: [customerID, tenure, MonthlyCharges, TotalCharges, Contract, Churn]
Index: []

In [53]:
len(suspicious_charges)

0

#Check categorical values

In [54]:
categorical_cols = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod",
    "Churn"
]

for col in categorical_cols:
    print(f"\n========== {col} ==========")
    print(df_clean[col].value_counts())

========== gender ==========
gender
Male      3555
Female    3488
Name: count, dtype: int64

========== Partner ==========
Partner
No     3641
Yes    3402
Name: count, dtype: int64

========== Dependents ==========
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

========== PhoneService ==========
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

========== MultipleLines ==========
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

========== InternetService ==========
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

========== OnlineSecurity ==========
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

========== OnlineBackup ==========
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

========== DeviceProtection ==========
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

========== TechSupport ==========
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

========== StreamingTV ==========
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

========== StreamingMovies ==========
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

========== Contract ==========
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

========== PaperlessBilling ==========
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

========== PaymentMethod ==========
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

========== Churn ==========
Churn
No     5174
Yes    1869
Name: count, dtype: int64

#Create a formal data-quality report

In [55]:
quality_report = pd.DataFrame({
    "Column": df_clean.columns,
    "Data_Type": df_clean.dtypes.astype(str).values,
    "Missing_Count": df_clean.isna().sum().values,
    "Unique_Values": df_clean.nunique().values
})

quality_report

              Column Data_Type  Missing_Count  Unique_Values
0         customerID       str              0           7043
1             gender       str              0              2
2      SeniorCitizen     int64              0              2
3            Partner       str              0              2
4         Dependents       str              0              2
5             tenure     int64              0             73
6       PhoneService       str              0              2
7      MultipleLines       str              0              3
8    InternetService       str              0              3
9     OnlineSecurity       str              0              3
10      OnlineBackup       str              0              3
11  DeviceProtection       str              0              3
12       TechSupport       str              0              3
13       StreamingTV       str              0              3
14   StreamingMovies       str              0              3
15          Contract       str              0              3
16  PaperlessBilling       str              0              2
17     PaymentMethod       str              0              4
18    MonthlyCharges   float64              0           1585
19      TotalCharges   float64              0           6531
20             Churn       str              0              2

In [53]:
quality_report.to_csv(
    "C:/Users/ekver/OneDrive/Documents/Job_Preparation/Customer_Retention_Project/data_quality_report.csv",
    index=False
)

In [56]:
df_clean["SeniorCitizen"].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [46]:
suspicious_charges = df_clean[
    (df_clean["tenure"] > 1) &
    (df_clean["TotalCharges"] < df_clean["MonthlyCharges"])
]

len(suspicious_charges)

0

In [47]:
# ==========================================
# FINAL DATA QUALITY VALIDATION
# ==========================================

print("========== DATASET SHAPE ==========")
print(df_clean.shape)

print("\n========== MISSING VALUES ==========")
print(df_clean.isna().sum())

print("\n========== DUPLICATE ROWS ==========")
print("Duplicate rows:", df_clean.duplicated().sum())

print("\n========== DUPLICATE CUSTOMER IDs ==========")
print("Duplicate customer IDs:", df_clean["customerID"].duplicated().sum())

print("\n========== DATA TYPES ==========")
print(df_clean.dtypes)

print("\n========== NUMERICAL RANGE CHECK ==========")

print("SeniorCitizen unique values:",
      sorted(df_clean["SeniorCitizen"].unique()))

print("Tenure range:",
      df_clean["tenure"].min(),
      "to",
      df_clean["tenure"].max())

print("MonthlyCharges range:",
      df_clean["MonthlyCharges"].min(),
      "to",
      df_clean["MonthlyCharges"].max())

print("TotalCharges range:",
      df_clean["TotalCharges"].min(),
      "to",
      df_clean["TotalCharges"].max())

print("\n========== BUSINESS LOGIC CHECK ==========")

# Customers with >1 month tenure should generally have
# TotalCharges >= MonthlyCharges
suspicious_charges = df_clean[
    (df_clean["tenure"] > 1) &
    (df_clean["TotalCharges"] < df_clean["MonthlyCharges"])
]

print("Suspicious TotalCharges records:",
      len(suspicious_charges))

print("\n========== CHURN DISTRIBUTION ==========")

print(df_clean["Churn"].value_counts())

print("\n========== CHURN RATE ==========")

churn_rate = (
    df_clean["Churn"].value_counts(normalize=True)["Yes"] * 100
)

print(f"Overall churn rate: {churn_rate:.2f}%")

========== DATASET SHAPE ==========
(7043, 21)

========== MISSING VALUES ==========
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

========== DUPLICATE ROWS ==========
Duplicate rows: 0

========== DUPLICATE CUSTOMER IDs ==========
Duplicate customer IDs: 0

========== DATA TYPES ==========
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

========== NUMERICAL RANGE CHECK ==========
SeniorCitizen unique values: [np.int64(0), np.int64(1)]
Tenure range: 0 to 72
MonthlyCharges range: 18.25 to 118.75
TotalCharges range: 0.0 to 8684.8

========== BUSINESS LOGIC CHECK ==========
Suspicious TotalCharges records: 0

========== CHURN DISTRIBUTION ==========
Churn
No     5174
Yes    1869
Name: count, dtype: int64

========== CHURN RATE ==========
Overall churn rate: 26.54%

======
STEP 2A — Numerical Anomaly Detection
========

In [48]:
# ==========================================
# STEP 2A — IQR OUTLIER DETECTION
# ==========================================

numerical_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

for col in numerical_cols:

    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_clean[
        (df_clean[col] < lower_bound) |
        (df_clean[col] > upper_bound)
    ]

    print(f"\n========== {col} ==========")

    print(f"Q1: {Q1:.2f}")
    print(f"Q3: {Q3:.2f}")
    print(f"IQR: {IQR:.2f}")

    print(f"Lower Bound: {lower_bound:.2f}")
    print(f"Upper Bound: {upper_bound:.2f}")

    print(f"Number of outliers: {len(outliers)}")
    print(f"Percentage of customers: {len(outliers) / len(df_clean) * 100:.2f}%")

========== tenure ==========
Q1: 9.00
Q3: 55.00
IQR: 46.00
Lower Bound: -60.00
Upper Bound: 124.00
Number of outliers: 0
Percentage of customers: 0.00%

========== MonthlyCharges ==========
Q1: 35.50
Q3: 89.85
IQR: 54.35
Lower Bound: -46.02
Upper Bound: 171.38
Number of outliers: 0
Percentage of customers: 0.00%

========== TotalCharges ==========
Q1: 398.55
Q3: 3786.60
IQR: 3388.05
Lower Bound: -4683.52
Upper Bound: 8868.67
Number of outliers: 0
Percentage of customers: 0.00%


### STEP 2B — Relationship-Based Anomaly Detection

In [49]:
# ==========================================
# STEP 2B — RELATIONSHIP-BASED ANOMALY CHECK
# ==========================================

df_anomaly = df_clean.copy()

# Approximate expected charges
df_anomaly["ExpectedCharges"] = (
    df_anomaly["MonthlyCharges"] *
    df_anomaly["tenure"]
)

# Difference between actual and approximate expected charges
df_anomaly["ChargeDifference"] = (
    df_anomaly["TotalCharges"] -
    df_anomaly["ExpectedCharges"]
)

# Percentage difference
df_anomaly["ChargeDifferencePct"] = (
    df_anomaly["ChargeDifference"] /
    df_anomaly["ExpectedCharges"].replace(0, np.nan)
) * 100

print("========== CHARGE RELATIONSHIP ==========")

print(
    df_anomaly[
        [
            "tenure",
            "MonthlyCharges",
            "TotalCharges",
            "ExpectedCharges",
            "ChargeDifference",
            "ChargeDifferencePct"
        ]
    ].describe().T
)

========== CHARGE RELATIONSHIP ==========
                      count         mean          std         min         25%  \
tenure               7043.0    32.371149    24.559481    0.000000    9.000000
MonthlyCharges       7043.0    64.761692    30.090047   18.250000   35.500000
TotalCharges         7043.0  2279.734304  2266.794470    0.000000  398.550000
ExpectedCharges      7043.0  2279.581350  2264.729447    0.000000  394.000000
ChargeDifference     7043.0     0.152953    67.202778 -370.850000  -28.600000
ChargeDifferencePct  7032.0     0.027482     5.115856  -31.064356   -2.045411

                         50%          75%          max
tenure                 29.00    55.000000    72.000000
MonthlyCharges         70.35    89.850000   118.750000
TotalCharges         1394.55  3786.600000  8684.800000
ExpectedCharges      1393.60  3786.100000  8550.000000
ChargeDifference        0.00    28.500000   373.250000
ChargeDifferencePct     0.00     1.956217    57.345361

In [50]:
# ==========================================
# CUSTOMERS WITH LARGEST CHARGE DIFFERENCES
# ==========================================

print("========== TOP 20 CHARGE DIFFERENCES ==========")

top_charge_diff = df_anomaly[
    df_anomaly["ExpectedCharges"] > 0
].sort_values(
    "ChargeDifferencePct",
    ascending=False
)

print(
    top_charge_diff[
        [
            "customerID",
            "tenure",
            "MonthlyCharges",
            "TotalCharges",
            "ExpectedCharges",
            "ChargeDifference",
            "ChargeDifferencePct",
            "Contract",
            "InternetService",
            "Churn"
        ]
    ].head(20)
)

========== TOP 20 CHARGE DIFFERENCES ==========
      customerID  tenure  MonthlyCharges  TotalCharges  ExpectedCharges  \
5595  2308-STERM       2           19.40         61.05            38.80
869   0323-XWWTN       3           26.40        121.25            79.20
5673  6260-XLACS       4           19.70        117.80            78.80
4689  2832-SCUCO       2           19.90         57.40            39.80
4634  9426-SXNHE       2           18.75         53.15            37.50
3945  3815-SLMEF       3           34.25        139.35           102.75
6828  2005-DWQZJ       8           19.05        201.70           152.40
6619  2791-SFVEW       9           20.15        238.15           181.35
4969  2303-PJYHN       2           19.85         52.00            39.70
2374  9101-NTIXF       2           19.40         50.60            38.80
6155  4903-UYAVB       5           19.35        126.05            96.75
2698  8150-QUDFX       2           19.85         51.60            39.70
3043  3677-IYRBF       2           30.40         78.65            60.80
3139  1142-WACZW       2           29.85         75.60            59.70
561   7343-EOBEU       3           23.60         89.05            70.80
1133  3156-QLHBO       2           19.25         48.35            38.50
6350  3407-QGWLG       3           20.05         75.45            60.15
1930  2792-VPPET       3           20.50         76.95            61.50
5311  8053-WWDRO       6           19.50        146.30           117.00
2504  8433-WXGNA       2           75.70        189.20           151.40

      ChargeDifference  ChargeDifferencePct        Contract InternetService  \
5595             22.25            57.345361  Month-to-month              No
869              42.05            53.093434        Two year              No
5673             39.00            49.492386        One year              No
4689             17.60            44.221106  Month-to-month              No
4634             15.65            41.733333  Month-to-month              No
3945             36.60            35.620438  Month-to-month             DSL
6828             49.30            32.349081        Two year              No
6619             56.80            31.320651  Month-to-month              No
4969             12.30            30.982368  Month-to-month              No
2374             11.80            30.412371  Month-to-month              No
6155             29.30            30.284238  Month-to-month              No
2698             11.90            29.974811  Month-to-month              No
3043             17.85            29.358553  Month-to-month             DSL
3139             15.90            26.633166  Month-to-month             DSL
561              18.25            25.776836  Month-to-month              No
1133              9.85            25.584416  Month-to-month              No
6350             15.30            25.436409  Month-to-month              No
1930             15.45            25.121951  Month-to-month              No
5311             29.30            25.042735  Month-to-month              No
2504             37.80            24.966975  Month-to-month     Fiber optic

     Churn
5595    No
869     No
5673    No
4689    No
4634    No
3945   Yes
6828    No
6619    No
4969    No
2374    No
6155   Yes
2698    No
3043   Yes
3139   Yes
561     No
1133    No
6350    No
1930    No
5311   Yes
2504   Yes

In [51]:
print("========== LOWEST CHARGE DIFFERENCES ==========")

bottom_charge_diff = df_anomaly[
    df_anomaly["ExpectedCharges"] > 0
].sort_values(
    "ChargeDifferencePct",
    ascending=True
)

print(
    bottom_charge_diff[
        [
            "customerID",
            "tenure",
            "MonthlyCharges",
            "TotalCharges",
            "ExpectedCharges",
            "ChargeDifference",
            "ChargeDifferencePct",
            "Contract",
            "InternetService",
            "Churn"
        ]
    ].head(20)
)

========== LOWEST CHARGE DIFFERENCES ==========
      customerID  tenure  MonthlyCharges  TotalCharges  ExpectedCharges  \
2950  3345-JHUEO       4           20.20         55.70            80.80
4203  4291-YZODP       7           20.05         96.80           140.35
900   1051-GEJLJ       2           19.50         27.55            39.00
4262  5485-WUYWF       2           66.40         94.55           132.80
3790  6598-RFFVI       2           19.30         28.30            38.60
5917  5144-PQCDZ       4           19.95         59.25            79.80
3408  2108-YKQTY       4           50.70        151.30           202.80
3621  2933-FILNV       2           24.40         36.55            48.80
124   7219-TLZHO       4           20.85         62.90            83.40
4487  4116-IQRFR       4           24.10         73.10            96.40
776   9505-SQFSW       3           40.30         92.50           120.90
6258  5066-GFJMM       3           19.90         45.75            59.70
1620  6022-KOUQO       2           29.05         44.75            58.10
4898  8993-PHFWD       3           25.25         58.90            75.75
1846  7369-TRPFD      19           18.80        279.20           357.20
3475  8610-ZIKJJ       2           20.30         31.90            40.60
3080  1777-JYQPJ       2           24.30         38.45            48.60
5661  4396-KLSEH       4           19.85         63.00            79.40
6158  3845-FXCYS       2           19.65         31.20            39.30
6829  8148-WOCMK       8           19.60        125.00           156.80

      ChargeDifference  ChargeDifferencePct        Contract InternetService  \
2950            -25.10           -31.064356  Month-to-month              No
4203            -43.55           -31.029569        One year              No
900             -11.45           -29.358974  Month-to-month              No
4262            -38.25           -28.802711  Month-to-month             DSL
3790            -10.30           -26.683938        One year              No
5917            -20.55           -25.751880  Month-to-month              No
3408            -51.50           -25.394477  Month-to-month             DSL
3621            -12.25           -25.102459  Month-to-month             DSL
124             -20.50           -24.580336  Month-to-month              No
4487            -23.30           -24.170124        One year              No
776             -28.40           -23.490488  Month-to-month             DSL
6258            -13.95           -23.366834  Month-to-month              No
1620            -13.35           -22.977625  Month-to-month             DSL
4898            -16.85           -22.244224  Month-to-month             DSL
1846            -78.00           -21.836506        One year              No
3475             -8.70           -21.428571        One year              No
3080            -10.15           -20.884774  Month-to-month             DSL
5661            -16.40           -20.654912  Month-to-month              No
6158             -8.10           -20.610687  Month-to-month              No
6829            -31.80           -20.280612        Two year              No

     Churn
2950    No
4203    No
900     No
4262   Yes
3790   Yes
5917    No
3408   Yes
3621   Yes
124     No
4487    No
776     No
6258    No
1620    No
4898   Yes
1846    No
3475    No
3080    No
5661    No
6158    No
6829    No

### STEP 2C — High-Value Churn Anomaly

High Monthly Charges
        +
Long Tenure
        +
Churn = Yes

In [53]:
# ==========================================
# STEP 2C — HIGH-VALUE CHURN CUSTOMERS
# ==========================================

# Find the 75th percentile of MonthlyCharges
high_value_threshold = df_clean["MonthlyCharges"].quantile(0.75)

# Find the 75th percentile of tenure
long_tenure_threshold = df_clean["tenure"].quantile(0.75)

high_value_churn = df_clean[
    (df_clean["MonthlyCharges"] >= high_value_threshold) &
    (df_clean["tenure"] >= long_tenure_threshold) &
    (df_clean["Churn"] == "Yes")
].copy()

print("========== HIGH-VALUE CHURN CUSTOMERS ==========")

print("High monthly charge threshold:",
      round(high_value_threshold, 2))

print("Long tenure threshold:",
      long_tenure_threshold)

print("Number of high-value churn customers:",
      len(high_value_churn))

print("\nPotential monthly revenue lost:")

print(
    round(high_value_churn["MonthlyCharges"].sum(), 2)
)

print("\nTop high-value churn customers:")

print(
    high_value_churn[
        [
            "customerID",
            "tenure",
            "MonthlyCharges",
            "TotalCharges",
            "Contract",
            "InternetService",
            "PaymentMethod",
            "Churn"
        ]
    ]
    .sort_values("MonthlyCharges", ascending=False)
    .head(20)
)

========== HIGH-VALUE CHURN CUSTOMERS ==========
High monthly charge threshold: 89.85
Long tenure threshold: 55.0
Number of high-value churn customers: 110

Potential monthly revenue lost:
11384.15

Top high-value churn customers:
      customerID  tenure  MonthlyCharges  TotalCharges        Contract  \
5127  8199-ZLLSA      67          118.35       7804.15        One year
4610  2889-FPWRM      72          117.80       8684.80        One year
6289  9053-JZFKV      67          116.20       7752.30        Two year
6537  1444-VVSGW      70          115.65       7968.85        One year
1306  0201-OAMXR      70          115.55       8127.60        One year
6038  1555-DJEQW      70          114.20       7723.90        Two year
5581  5271-YNWVR      68          113.15       7856.00        Two year
2424  5236-PERKL      57          112.95       6465.00        Two year
6972  6664-FPDAC      56          111.95       6418.90        One year
6785  3090-HAWSU      61          111.60       6876.05        Two year
2204  2659-VXMWZ      67          111.30       7482.10        One year
6605  7632-MNYOY      66          110.90       7432.05        One year
6035  9835-ZIITK      66          110.85       7491.75        One year
1268  2408-TZMJL      59          110.15       6448.05        One year
104   3192-NQECA      68          110.00       7611.85        Two year
5697  1984-FCOWB      70          109.50       7674.55        One year
3517  0748-RDGGM      70          109.50       7534.65        One year
3849  5089-IFSDP      58          109.45       6144.55        Two year
3890  3886-CERTZ      72          109.25       8109.80        One year
2277  3571-RFHAR      65          109.15       6941.20  Month-to-month

     InternetService              PaymentMethod Churn
5127     Fiber optic  Bank transfer (automatic)   Yes
4610     Fiber optic  Bank transfer (automatic)   Yes
6289     Fiber optic    Credit card (automatic)   Yes
6537     Fiber optic    Credit card (automatic)   Yes
1306     Fiber optic    Credit card (automatic)   Yes
6038     Fiber optic  Bank transfer (automatic)   Yes
5581     Fiber optic           Electronic check   Yes
2424     Fiber optic  Bank transfer (automatic)   Yes
6972     Fiber optic           Electronic check   Yes
6785     Fiber optic    Credit card (automatic)   Yes
2204     Fiber optic           Electronic check   Yes
6605     Fiber optic    Credit card (automatic)   Yes
6035     Fiber optic           Electronic check   Yes
1268     Fiber optic           Electronic check   Yes
104      Fiber optic  Bank transfer (automatic)   Yes
5697     Fiber optic           Electronic check   Yes
3517     Fiber optic  Bank transfer (automatic)   Yes
3849     Fiber optic  Bank transfer (automatic)   Yes
3890     Fiber optic           Electronic check   Yes
2277     Fiber optic           Electronic check   Yes

In [54]:
# ==========================================
# EARLY-TENURE CHURN
# ==========================================

early_churn = df_clean[
    (df_clean["tenure"] <= 6) &
    (df_clean["Churn"] == "Yes")
].copy()

print("========== EARLY-TENURE CHURN ==========")

print("Early churn customers:",
      len(early_churn))

print("Percentage of all churn:",
      round(
          len(early_churn) /
          len(df_clean[df_clean["Churn"] == "Yes"]) * 100,
          2
      ),
      "%")

print("\nAverage monthly charge of early churn customers:",
      round(early_churn["MonthlyCharges"].mean(), 2))

========== EARLY-TENURE CHURN ==========
Early churn customers: 784
Percentage of all churn: 41.95 %

Average monthly charge of early churn customers: 63.64

## STEP 3 — Exploratory Data Analysis

#### Step 3A — Start with the most basic business KPI

In [55]:
# ==========================================
# STEP 3A — CORE BUSINESS KPIs
# ==========================================

total_customers = df_clean["customerID"].nunique()

churned_customers = (
    df_clean[df_clean["Churn"] == "Yes"]["customerID"].nunique()
)

active_customers = (
    df_clean[df_clean["Churn"] == "No"]["customerID"].nunique()
)

churn_rate = churned_customers / total_customers * 100

monthly_revenue = df_clean["MonthlyCharges"].sum()

monthly_revenue_lost = (
    df_clean.loc[
        df_clean["Churn"] == "Yes",
        "MonthlyCharges"
    ].sum()
)

annual_revenue_lost = monthly_revenue_lost * 12

print("========== CORE BUSINESS KPIs ==========")

print(f"Total customers: {total_customers:,}")

print(f"Active customers: {active_customers:,}")

print(f"Churned customers: {churned_customers:,}")

print(f"Churn rate: {churn_rate:.2f}%")

print(f"Total monthly revenue: {monthly_revenue:,.2f}")

print(f"Monthly revenue from churned customers: "
      f"{monthly_revenue_lost:,.2f}")

print(f"Annualized revenue exposure: "
      f"{annual_revenue_lost:,.2f}")

========== CORE BUSINESS KPIs ==========
Total customers: 7,043
Active customers: 5,174
Churned customers: 1,869
Churn rate: 26.54%
Total monthly revenue: 456,116.60
Monthly revenue from churned customers: 139,130.85
Annualized revenue exposure: 1,669,570.20

#### Step 3B — Churn by Contract Type

Does contract type influence churn?

In [56]:
# ==========================================
# STEP 3B — CHURN BY CONTRACT
# ==========================================

contract_analysis = (
    df_clean
    .groupby("Contract")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

contract_analysis["ChurnRate"] = (
    contract_analysis["ChurnedCustomers"] /
    contract_analysis["TotalCustomers"] * 100
)

contract_analysis["RevenueFromChurnedCustomers"] = (
    df_clean[df_clean["Churn"] == "Yes"]
    .groupby("Contract")["MonthlyCharges"]
    .sum()
    .reindex(contract_analysis["Contract"])
    .fillna(0)
    .values
)

contract_analysis = contract_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(contract_analysis)

         Contract  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0  Month-to-month            3875              1655       257294.15
1        One year            1473               166        95816.60
2        Two year            1695                48       103005.85

   ChurnRate  RevenueFromChurnedCustomers
0  42.709677                    120847.10
1  11.269518                     14118.45
2   2.831858                      4165.30

#### Step 3C — Churn by Tenure

In [58]:
tenure_analysis = (
    df_clean
    .groupby("tenure")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

tenure_analysis["ChurnRate"] = (
    tenure_analysis["ChurnedCustomers"] /
    tenure_analysis["TotalCustomers"] * 100
)

print(tenure_analysis.head(15))

    tenure  TotalCustomers  ChurnedCustomers  ChurnRate
0        0              11                 0   0.000000
1        1             613               380  61.990212
2        2             238               123  51.680672
3        3             200                94  47.000000
4        4             176                83  47.159091
5        5             133                64  48.120301
6        6             110                40  36.363636
7        7             131                51  38.931298
8        8             123                42  34.146341
9        9             119                46  38.655462
10      10             116                45  38.793103
11      11              99                31  31.313131
12      12             117                38  32.478632
13      13             109                38  34.862385
14      14              76                24  31.578947

In [59]:
df_clean["TenureGroup"] = pd.cut(
    df_clean["tenure"],
    bins=[-1, 6, 12, 24, 48, 72],
    labels=[
        "0-6 months",
        "7-12 months",
        "13-24 months",
        "25-48 months",
        "49-72 months"
    ]
)

tenure_group_analysis = (
    df_clean
    .groupby("TenureGroup", observed=True)
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

tenure_group_analysis["ChurnRate"] = (
    tenure_group_analysis["ChurnedCustomers"] /
    tenure_group_analysis["TotalCustomers"] * 100
)

print(tenure_group_analysis)

    TenureGroup  TotalCustomers  ChurnedCustomers  MonthlyRevenue  ChurnRate
0    0-6 months            1481               784        81067.95  52.937205
1   7-12 months             705               253        41561.80  35.886525
2  13-24 months            1024               294        62829.85  28.710938
3  25-48 months            1594               325       105093.30  20.388959
4  49-72 months            2239               213       165563.70   9.513176

In [60]:
contract_tenure_analysis = (
    df_clean
    .groupby(["TenureGroup", "Contract"], observed=True)
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

contract_tenure_analysis["ChurnRate"] = (
    contract_tenure_analysis["ChurnedCustomers"] /
    contract_tenure_analysis["TotalCustomers"] * 100
)

print(contract_tenure_analysis)

     TenureGroup        Contract  TotalCustomers  ChurnedCustomers  ChurnRate
0     0-6 months  Month-to-month            1413               780  55.201699
1     0-6 months        One year              39                 4  10.256410
2     0-6 months        Two year              29                 0   0.000000
3    7-12 months  Month-to-month             581               244  41.996558
4    7-12 months        One year              85                 9  10.588235
5    7-12 months        Two year              39                 0   0.000000
6   13-24 months  Month-to-month             737               278  37.720488
7   13-24 months        One year             197                16   8.121827
8   13-24 months        Two year              90                 0   0.000000
9   25-48 months  Month-to-month             802               264  32.917706
10  25-48 months        One year             518                55  10.617761
11  25-48 months        Two year             274                 6   2.189781
12  49-72 months  Month-to-month             342                89  26.023392
13  49-72 months        One year             634                82  12.933754
14  49-72 months        Two year            1263                42   3.325416

#### Step 3D — Payment Method & Churn

In [61]:
payment_analysis = (
    df_clean
    .groupby("PaymentMethod")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

payment_analysis["ChurnRate"] = (
    payment_analysis["ChurnedCustomers"] /
    payment_analysis["TotalCustomers"] * 100
)

payment_analysis = payment_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(payment_analysis)

               PaymentMethod  TotalCustomers  ChurnedCustomers  \
2           Electronic check            2365              1071
3               Mailed check            1612               308
0  Bank transfer (automatic)            1544               258
1    Credit card (automatic)            1522               232

   MonthlyRevenue  ChurnRate
2       180345.00  45.285412
3        70794.30  19.106700
0       103745.45  16.709845
1       101231.85  15.243101

Electronic-check customers exhibit substantially higher observed churn than customers using other payment methods, indicating payment method may be an important churn-risk indicator.

In [62]:
payment_contract_analysis = (
    df_clean
    .groupby(["PaymentMethod", "Contract"])
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum())
    )
    .reset_index()
)

payment_contract_analysis["ChurnRate"] = (
    payment_contract_analysis["ChurnedCustomers"] /
    payment_contract_analysis["TotalCustomers"] * 100
)

payment_contract_analysis = payment_contract_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(payment_contract_analysis)

                PaymentMethod        Contract  TotalCustomers  \
6            Electronic check  Month-to-month            1850
0   Bank transfer (automatic)  Month-to-month             589
3     Credit card (automatic)  Month-to-month             543
9                Mailed check  Month-to-month             893
7            Electronic check        One year             347
4     Credit card (automatic)        One year             398
1   Bank transfer (automatic)        One year             391
8            Electronic check        Two year             168
10               Mailed check        One year             337
2   Bank transfer (automatic)        Two year             564
5     Credit card (automatic)        Two year             581
11               Mailed check        Two year             382

    ChurnedCustomers  ChurnRate
6                994  53.729730
0                201  34.125637
3                178  32.780847
9                282  31.578947
7                 64  18.443804
4                 41  10.301508
1                 38   9.718670
8                 13   7.738095
10                23   6.824926
2                 19   3.368794
5                 13   2.237522
11                 3   0.785340

#### Step 3F — Internet Service & Churn

In [63]:
internet_analysis = (
    df_clean
    .groupby("InternetService")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

internet_analysis["ChurnRate"] = (
    internet_analysis["ChurnedCustomers"] /
    internet_analysis["TotalCustomers"] * 100
)

internet_analysis = internet_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(internet_analysis)

  InternetService  TotalCustomers  ChurnedCustomers  MonthlyRevenue  ChurnRate
1     Fiber optic            3096              1297       283284.40  41.892765
0             DSL            2421               459       140665.35  18.959108
2              No            1526               113        32166.85   7.404980

In [64]:
fiber_contract_analysis = (
    df_clean
    .groupby(["InternetService", "Contract"])
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

fiber_contract_analysis["ChurnRate"] = (
    fiber_contract_analysis["ChurnedCustomers"] /
    fiber_contract_analysis["TotalCustomers"] * 100
)

fiber_contract_analysis = fiber_contract_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(fiber_contract_analysis)

  InternetService        Contract  TotalCustomers  ChurnedCustomers  \
3     Fiber optic  Month-to-month            2128              1162
0             DSL  Month-to-month            1223               394
4     Fiber optic        One year             539               104
6              No  Month-to-month             524                99
1             DSL        One year             570                53
5     Fiber optic        Two year             429                31
7              No        One year             364                 9
2             DSL        Two year             628                12
8              No        Two year             638                 5

   MonthlyRevenue  ChurnRate
3       185181.10  54.605263
0        61418.45  32.215863
4        53242.15  19.294991
6        10694.60  18.893130
1        34996.15   9.298246
5        44861.15   7.226107
7         7578.30   2.472527
2        44250.75   1.910828
8        13893.95   0.783699

#### Step 3H — Service Features & Churn

In [65]:
security_analysis = (
    df_clean
    .groupby("OnlineSecurity")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

security_analysis["ChurnRate"] = (
    security_analysis["ChurnedCustomers"] /
    security_analysis["TotalCustomers"] * 100
)

security_analysis = security_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(security_analysis)

        OnlineSecurity  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            3498              1461       264774.35
2                  Yes            2019               295       159175.40
1  No internet service            1526               113        32166.85

   ChurnRate
0  41.766724
2  14.611194
1   7.404980

In [66]:
support_analysis = (
    df_clean
    .groupby("TechSupport")
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

support_analysis["ChurnRate"] = (
    support_analysis["ChurnedCustomers"] /
    support_analysis["TotalCustomers"] * 100
)

support_analysis = support_analysis.sort_values(
    "ChurnRate",
    ascending=False
)

print(support_analysis)

           TechSupport  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            3473              1446       259039.55
2                  Yes            2044               310       164910.20
1  No internet service            1526               113        32166.85

   ChurnRate
0  41.635474
2  15.166341
1   7.404980

Customers without online security and technical support exhibit substantially higher observed churn rates than customers subscribed to these services. These service attributes may therefore serve as useful churn-risk indicators and warrant further investigation.

#### Step 3I — Revenue / Monthly Charges

In [67]:
df_clean["MonthlyChargeGroup"] = pd.qcut(
    df_clean["MonthlyCharges"],
    q=4,
    labels=[
        "Low",
        "Medium-Low",
        "Medium-High",
        "High"
    ]
)

charge_analysis = (
    df_clean
    .groupby("MonthlyChargeGroup", observed=True)
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        AvgMonthlyCharges=("MonthlyCharges", "mean"),
        MonthlyRevenue=("MonthlyCharges", "sum")
    )
    .reset_index()
)

charge_analysis["ChurnRate"] = (
    charge_analysis["ChurnedCustomers"] /
    charge_analysis["TotalCustomers"] * 100
)

print(charge_analysis)

  MonthlyChargeGroup  TotalCustomers  ChurnedCustomers  AvgMonthlyCharges  \
0                Low            1762               198          22.230306
1         Medium-Low            1766               434          55.729360
2        Medium-High            1757               659          80.334861
3               High            1758               578         100.898976

   MonthlyRevenue  ChurnRate
0        39169.80  11.237230
1        98418.05  24.575311
2       141148.35  37.507114
3       177380.40  32.878271

#### Step 3J — Analyze Other Services

In [68]:
service_columns = [
    "OnlineBackup",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies"
]

for col in service_columns:
    
    service_analysis = (
        df_clean
        .groupby(col)
        .agg(
            TotalCustomers=("customerID", "nunique"),
            ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
            MonthlyRevenue=("MonthlyCharges", "sum")
        )
        .reset_index()
    )

    service_analysis["ChurnRate"] = (
        service_analysis["ChurnedCustomers"] /
        service_analysis["TotalCustomers"] * 100
    )

    print(f"\n{'='*50}")
    print(f"{col}")
    print(f"{'='*50}")
    print(service_analysis)

==================================================
OnlineBackup
==================================================
          OnlineBackup  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            3088              1233       222144.55
1  No internet service            1526               113        32166.85
2                  Yes            2429               523       201805.20

   ChurnRate
0  39.928756
1   7.404980
2  21.531494

==================================================
DeviceProtection
==================================================
      DeviceProtection  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            3095              1211       218510.25
1  No internet service            1526               113        32166.85
2                  Yes            2422               545       205439.50

   ChurnRate
0  39.127625
1   7.404980
2  22.502064

==================================================
StreamingTV
==================================================
           StreamingTV  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            2810               942       183739.40
1  No internet service            1526               113        32166.85
2                  Yes            2707               814       240210.35

   ChurnRate
0  33.523132
1   7.404980
2  30.070188

==================================================
StreamingMovies
==================================================
       StreamingMovies  TotalCustomers  ChurnedCustomers  MonthlyRevenue  \
0                   No            2785               938       182234.10
1  No internet service            1526               113        32166.85
2                  Yes            2732               818       241715.65

   ChurnRate
0  33.680431
1   7.404980
2  29.941435

#### Step 3K — Find the Highest-Risk Customer Segments

In [70]:
risk_segment = (
    df_clean
    .groupby(
        ["Contract", "InternetService", "PaymentMethod"]
    )
    .agg(
        TotalCustomers=("customerID", "nunique"),
        ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum()),
        MonthlyRevenue=("MonthlyCharges", "sum"),
        ChurnedMonthlyRevenue=(
            "MonthlyCharges",
            lambda x: x[df_clean.loc[x.index, "Churn"] == "Yes"].sum()
        )
    )
    .reset_index()
)

risk_segment["ChurnRate"] = (
    risk_segment["ChurnedCustomers"] /
    risk_segment["TotalCustomers"] * 100
)

risk_segment = risk_segment.sort_values(
    "ChurnRate",
    ascending=False
)

print(risk_segment.head(15))

          Contract InternetService              PaymentMethod  TotalCustomers  \
6   Month-to-month     Fiber optic           Electronic check            1307
7   Month-to-month     Fiber optic               Mailed check             201
4   Month-to-month     Fiber optic  Bank transfer (automatic)             327
5   Month-to-month     Fiber optic    Credit card (automatic)             293
2   Month-to-month             DSL           Electronic check             474
3   Month-to-month             DSL               Mailed check             367
1   Month-to-month             DSL    Credit card (automatic)             185
18        One year     Fiber optic           Electronic check             196
11  Month-to-month              No               Mailed check             325
8   Month-to-month              No  Bank transfer (automatic)              65
0   Month-to-month             DSL  Bank transfer (automatic)             197
19        One year     Fiber optic               Mailed check              36
10  Month-to-month              No           Electronic check              69
17        One year     Fiber optic    Credit card (automatic)             150
16        One year     Fiber optic  Bank transfer (automatic)             157

    ChurnedCustomers  MonthlyRevenue  ChurnedMonthlyRevenue  ChurnRate
6                789       113948.10               68281.50  60.367253
7                102        16600.15                8407.25  50.746269
4                149        28859.00               13062.10  45.565749
5                122        25773.85               10731.15  41.638225
2                192        23342.45                8776.45  40.506329
3                113        17924.10                5292.10  30.790191
1                 50         9650.85                2474.80  27.027027
18                51        19435.50                5149.65  26.020408
11                67         6598.45                1345.05  20.615385
8                 13         1331.25                 265.95  20.000000
0                 39        10501.05                1823.90  19.796954
19                 7         3518.60                 685.60  19.444444
10                13         1440.00                 257.65  18.840580
17                23        14874.70                2392.35  15.333333
16                23        15413.35                2344.35  14.649682

The highest observed churn concentration occurs among month-to-month fiber-optic customers, particularly those using electronic check payments.

#### Step 3L — Final EDA: Churn Driver Summary

In [71]:
churn_summary = []

features = [
    "Contract",
    "PaymentMethod",
    "InternetService",
    "OnlineSecurity",
    "TechSupport",
    "OnlineBackup",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies"
]

for feature in features:

    temp = (
        df_clean
        .groupby(feature)
        .agg(
            TotalCustomers=("customerID", "nunique"),
            ChurnedCustomers=("Churn", lambda x: (x == "Yes").sum())
        )
        .reset_index()
    )

    temp["ChurnRate"] = (
        temp["ChurnedCustomers"] /
        temp["TotalCustomers"] * 100
    )

    temp["Feature"] = feature
    temp["Segment"] = temp[feature].astype(str)

    churn_summary.append(
        temp[
            [
                "Feature",
                "Segment",
                "TotalCustomers",
                "ChurnedCustomers",
                "ChurnRate"
            ]
        ]
    )

churn_summary = pd.concat(
    churn_summary,
    ignore_index=True
)

churn_summary = churn_summary.sort_values(
    "ChurnRate",
    ascending=False
)

print(churn_summary.head(25))

             Feature                    Segment  TotalCustomers  \
5      PaymentMethod           Electronic check            2365
0           Contract             Month-to-month            3875
8    InternetService                Fiber optic            3096
10    OnlineSecurity                         No            3498
13       TechSupport                         No            3473
16      OnlineBackup                         No            3088
19  DeviceProtection                         No            3095
25   StreamingMovies                         No            2785
22       StreamingTV                         No            2810
24       StreamingTV                        Yes            2707
27   StreamingMovies                        Yes            2732
21  DeviceProtection                        Yes            2422
18      OnlineBackup                        Yes            2429
6      PaymentMethod               Mailed check            1612
7    InternetService                        DSL            2421
3      PaymentMethod  Bank transfer (automatic)            1544
4      PaymentMethod    Credit card (automatic)            1522
15       TechSupport                        Yes            2044
12    OnlineSecurity                        Yes            2019
1           Contract                   One year            1473
17      OnlineBackup        No internet service            1526
11    OnlineSecurity        No internet service            1526
9    InternetService                         No            1526
14       TechSupport        No internet service            1526
23       StreamingTV        No internet service            1526

    ChurnedCustomers  ChurnRate
5               1071  45.285412
0               1655  42.709677
8               1297  41.892765
10              1461  41.766724
13              1446  41.635474
16              1233  39.928756
19              1211  39.127625
25               938  33.680431
22               942  33.523132
24               814  30.070188
27               818  29.941435
21               545  22.502064
18               523  21.531494
6                308  19.106700
7                459  18.959108
3                258  16.709845
4                232  15.243101
15               310  15.166341
12               295  14.611194
1                166  11.269518
17               113   7.404980
11               113   7.404980
9                113   7.404980
14               113   7.404980
23               113   7.404980

In [72]:
df_clean.to_csv(
    "C:/Users/ekver/OneDrive/Documents/Job_Preparation/Customer_Retention_Project/telco_churn_cleaned.csv",
    index=False
)

In [58]:
# Install required libraries

from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
username = "postgres"
password = "ravenclawn"
host = "localhost"
port = "5432"
database = "customer_retention"

# Create connection
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df_clean.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_retention'.

In [60]:
# Create a copy for SQL
df_sql = df_clean.copy()





# Convert column names to lowercase
df_sql.columns = df_sql.columns.str.lower()

# Replace any spaces with underscores
df_sql.columns = (
    df_sql.columns
    .str.strip()
    .str.replace(" ", "_")
)

# Display columns
print(df_sql.columns.tolist())

['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents', 'tenure', 'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod', 'monthlycharges', 'totalcharges', 'churn']

In [61]:
print("Rows:", len(df_sql))
print("Columns:", len(df_sql.columns))
print("\nData types:")
print(df_sql.dtypes)

Rows: 7043
Columns: 21

Data types:
customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges        float64
churn                   str
dtype: object

In [62]:
df_sql.to_csv(
    "telco_churn_sql_ready.csv",
    index=False
)

print("SQL-ready CSV created successfully.")

SQL-ready CSV created successfully.

In [63]:
# Install required libraries

from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
username = "postgres"
password = "ravenclawn"
host = "localhost"
port = "5432"
database = "customer_retention"

# Create connection
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df_sql.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_retention'.